build:
    environment:
        php:
            version: 7.1
    dependencies:
        before:
            - composer install
    tests:
        override:
            -   command: 'phpunit --coverage-clover=build/clover.xml'
                coverage:
                    file: 'build/clover.xml'
                    format: 'clover'
