build:
    environment:
        php:
            version: 7.1
    dependencies:
        before:
            - composer install
    tests:
        override:
            -   command: 'phpunit --coverage-clover=build/clover.xml'
                coverage:
                    file: 'build/clover.xml'
                    format: 'clover'
filter:
    excluded_paths:
        - 'tests/*'
checks:
    php:
        use_self_instead_of_fqcn: true
        uppercase_constants: true
        return_doc_comments: true
        return_doc_comment_if_not_inferrable: true
        properties_in_camelcaps: true
        parameters_in_camelcaps: true
        parameter_doc_comments: true
        param_doc_comment_if_not_inferrable: true
        optional_parameters_at_the_end: true
        no_short_method_names:
            minimum: '3'
        no_short_variable_names:
            minimum: '3'
        no_long_variable_names:
            maximum: '20'
        no_goto: true
        newline_at_end_of_file: true
        function_in_camel_caps: true
        encourage_single_quotes: true
        custom_coding_standard:
            ruleset_path: 'phpcs.xml'
        classes_in_camel_caps: true
        check_method_contracts:
            verify_interface_like_constraints: true
            verify_documented_constraints: true
            verify_parent_constraints: true
        avoid_perl_style_comments: true
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
