language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  - nightly

before_script:
  - composer install
  - git config --global user.name travis-ci
  - git config --global user.email travis@example.com

script:
  - ./vendor/bin/phpunit tests/
  - ./vendor/bin/phpcs --standard=PSR2 src/ tests/

git:
  depth: 1

